### ISSUE TITLE
Check 51 staging

### ISSUE THREAD

**Issue by sr320** [RobertsLab/project-geoduck-repro#2]

**Comment by grace-ac** [comment]
What do I need to check?

**Comment by sr320** [comment]
Would it not be late  (not mid)?

https://github.com/RobertsLab/project-geoduck-repro/blob/master/Geoduck%20Hemolymph%20Samples%20-%20Sheet1.tsv

**Comment by grace-ac** [comment]
You are so right! I tried to edit it on the link above.

**Comment by sr320** [comment]
Also might be good to check others-

**Comment by grace-ac** [comment]
I checked others and all are correct. I couldn't edit the link you sent above, but I changed it in my google sheet that I shared with you
