### ISSUE TITLE
Get Box of hemolymph samples for analysis

### ISSUE THREAD

**Issue by sr320** [RobertsLab/project-geoduck-repro#3]
@grace-ac - could you please get a box of samples ready to hand off to Emma  before next Wednesday.

The samples we want are all the ones that correspond to the proteomics samples - PLUS three males and three females classified as early stage. 

thanks

**Comment by grace-ac** [comment]
Where would i be able to find an empty box to use?

**Comment by grace-ac** [comment]
never mind! i found an old box i used during my capstone i can re-label

**Comment by grace-ac** [comment]
I made a labeled box that's on the second shelf in the -80.

**Comment by sr320** [comment]
Thanks - note that one hemolymph was "bad" according to Emma - so I gave her female number 25
