### ISSUE TITLE
Confirm samples used for gonad RNA-seq libraries

### ISSUE THREAD

**Issue by sr320** [RobertsLab/project-geoduck-repro#4]
Please list sample IDs and where this info was obtained (url). Something to consider in database conversation.

**Comment by kubu4** [comment]
[Notebook entry](http://onsnetwork.org/kubu4/2015/06/01/sample-submission-geoduck-gonad-for-rna-seq/)

Google Sheet: [20150601_Geoduck_GENEWIZ_calcs](https://docs.google.com/spreadsheets/d/1cqVdYkTjzxc0TI2RV7EAxwO9_yqlKrvWSs4EIDC0WdY/edit#gid=0)

| Gender | Sample |
| --- | --- |
| f | DNased RNA Geoduck Gonad Block 08 |
| f | DNased RNA Geoduck Gonad Block 34 |
| f | DNased RNA Geoduck Gonad Block 35 |
| f | DNased RNA Geoduck Gonad Block 38 |
| f | DNased RNA Geoduck Gonad Block 51 |
| f | DNased RNA Geoduck Gonad Block 69 |
| f | DNased RNA Geoduck Gonad Block 70 |
| m | DNased RNA Geoduck Gonad Block 02 |
| m | DNased RNA Geoduck Gonad Block 07 |
| m | DNased RNA Geoduck Gonad Block 09 |
| m | DNased RNA Geoduck Gonad Block 41 |
| m | DNased RNA Geoduck Gonad Block 42 |
| m | DNased RNA Geoduck Gonad Block 46 |

**Comment by sr320** [comment]
Thanks!

**Comment by sr320** [comment]
@grace-ac Can you please provide stages for each of these samples (and provide url where you obtained this info?)

**Comment by kubu4** [comment]
Do we want to flesh out the wiki aspect of this project, similar to the other projects?

**Comment by sr320** [comment]
Yes- that would probably make sense

**Comment by grace-ac** [comment]
fGeo-08     early (s1)
fGeo-34     mid (s5)
fGeo-35     mid (s5)
fGeo-38     mid (s5)
fGeo-51     late (s6)
fGeo-69     late (s6)
fGeo-70     late (s6)
google sheet: https://docs.google.com/spreadsheets/d/1vrOQzLtsHykvrjqjODpKF5XSSYrq79xjPQl7ELwiVJY/edit#gid=0

mGeo-02     early (s1)
mGeo-07     early (s1)
mGeo-09     early (s1)
mGeo-41     mid (s3)
mGeo-42     mid (s3)
mGeo-46     mid (s3)
google sheet: 
https://docs.google.com/spreadsheets/d/1QGwwc1auce2PwbBsXrbmWRTAPDVJdAwXiEKh8qcdAuk/edit#gid=0

is that what you wanted?

**Comment by sr320** [comment]
👍

**Comment by sr320** [comment]
👍
